services:
  validator-backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'

    environment:
      - NODE_ENV=development

  validator-database:
    image: postgres:12
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: validator
